#!/bin/bash
find -type f -name "*.gif" | rev | cut -d "/" -f 1 | cut -d '.' -f 2- | rev | LC_ALL=C sort -f


shopt -s globstar nullglob

for file in **/*.gif; do
  if [ -f "$file" ]; then
    filename=$(echo "$file" | sed -e 's/\.gif$//I')
    echo "$filename"
  fi
done | LC_ALL=C sort -f

echo
